title: 'Zarathar'
tagline: 'Campagne de jeu de rôle'
base_url: 'https://christianamauger.com'
blog_url: '/blog'
glossary_url: '/glossaire'
author: 'Christian Amauger'

languages: ['fr']
default_lang: 'fr'
language_names:
  fr: 'Français'
  en: 'English'
year: 2025

social_media:
  github:
    url: 'https://github.com/camauger'
    name: 'GitHub'
  bsky:
    url: 'https://bsky.app/profile/christianamauger.itch.io'
    name: 'Bluesky'

default_description: 'Campagne de jeu de rôle Zarathar'
author: 'Christian Amauger'
keywords: 'zarathar, jeu de rôle, campagne, rpg, roleplaying game'
